# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'easyweather' do
  # Comment the next line if you don't want to use dynamic frameworks
  :modular_headers

  # Pods for easyweather
pod 'Firebase/Analytics'
end
